
build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker build -t awsebcli .
  - docker run --rm -i awsebcli eb --version
  only:
  - master

tag:
  stage: deploy
  image: alpine:latest
  script:
  - apk add --no-cache git openssh-client
  - git config --global user.email "ci@gitlab.com"
  - git config --global user.name "GitLab CI"
  - GIT_TAG=$(cat requirements.txt)
  - GIT_TAG=${GIT_TAG#awsebcli==}
  - git tag -f "$GIT_TAG" -a -m "AWS EB CLI v$GIT_TAG"
  - mkdir -p ~/.ssh/
  - printf "%s" "$SSH_KEY_PEM_BASE64" | base64 -d > ~/.ssh/id_rsa
  - chmod 400  ~/.ssh/id_rsa
  - SSH_REMOTE=ssh://git@github.com/sgreben/docker-awsebcli.git
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git push "$SSH_REMOTE" :"$GIT_TAG" || true
  - git push "$SSH_REMOTE" "$GIT_TAG"
  only:
  - master
